### ISSUE TITLE
Unable to use 'xray' reporter

### ISSUE THREAD

**Issue by vsridhargovx** [antreyes/testcafe-reporter-xray#5]
Hello @antreyes , I was able to install your TestCafe report -> Xray report plugin through your GIT URL, but on updating the reporter to use 'xray', am getting the below. 

```
On trying to use NPM to fetch your plugin, am getting a 404
npm install testcafe-reporter-xray
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/testcafe-reporter-xray - Not found
npm ERR! 404 
npm ERR! 404  'testcafe-reporter-xray@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

```
Error: The provided "xray" reporter does not exist. Check that you have specified the report format correctly.
    at requireReporterPluginFactory (/Users/vsridhar/IdeaProjects/ptf-testcafe/node_modules/testcafe/src/utils/reporter.ts:10:15)
    at Object.getPluginFactory (/Users/vsridhar/IdeaProjects/ptf-testcafe/node_modules/testcafe/src/utils/reporter.ts:16:16)
    at /Users/vsridhar/IdeaProjects/ptf-testcafe/node_modules/testcafe/src/runner/bootstrapper.ts:289:35
    at Array.map (<anonymous>)
    at Bootstrapper._getReporterPlugins (/Users/vsridhar/IdeaProjects/ptf-testcafe/node_modules/testcafe/src/runner/bootstrapper.ts:288:43)
    at Bootstrapper.createRunnableConfiguration (/Users/vsridhar/IdeaProjects/ptf-testcafe/node_modules/testcafe/src/runner/bootstrapper.ts:390:48)
    at GherkinTestcafeRunner._createRunnableConfiguration (/Users/vsridhar/IdeaProjects/ptf-testcafe/node_modules/testcafe/src/runner/index.js:328:14)
    at /Users/vsridhar/IdeaProjects/ptf-testcafe/node_modules/testcafe/src/runner/index.js:498:30
    at processTicksAndRejections (internal/process/task_queues.js:97:5)'''
```

**Comment by PaulMEdwards** [comment]
This URL exists: https://registry.npmjs.org/@antonio.reyes/testcafe-reporter-xray
You need to use the full package name: `@antonio.reyes/testcafe-reporter-xray`...

`npm install @antonio.reyes/testcafe-reporter-xray`

**Comment by PaulMEdwards** [comment]
OK, so it can be installed using the full name as I indicated above, but it seems unusable.

According to the TestCafe Reporter Plugin documentation:

> Important
> If you name the reporter package manually, its name must begin with the testcafe-reporter- prefix. Otherwise, TestCafe will be unable to recognize the plugin.

When I tried using the 'xray' reporter after installing it, TestCafe said it couldn't find that reporter plugin.

**Comment by PaulMEdwards** [comment]
This one works:

https://github.com/S1moB/testcafe-reporter-xray-json

**Comment by vsridhargovx** [comment]
Thanks, Paul - will try it out and let you know.

Thanks,

Vignesh Sridhar
+1-972-971-8215
